# Generated by Django 4.2.1 on 2023-05-07 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('encodings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
            ],
        ),
    ]
