# Generated by Django 4.2.1 on 2023-05-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='encodings',
            new_name='encoding',
        ),
    ]
